name: PHPUnit Tests

on:
  push: {}

jobs:
  phpunit:
    strategy:
      matrix:
        php-version: [7.4, 8.0, 8.1, 8.2]
        test-type: [unit, integration]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: Run ${{ matrix.test-type }} tests
        run: vendor/bin/phpunit
