name: Release

on:
  push:
    branches:
#      - main

jobs:
  run:
#    if: github.repository == 'supabase-community/supabase-php'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@2.22.0
        with:
          php-version: '8.1'
          extensions: curl

      - name: Echo 
        run: echo "${{ github.repository_owner }}" 

      - name: Install dependencies
        run: composer install

      - name: Test Code
        run: ./vendor/bin/phpunit
