name: Unit and Integration Test 
  on:
  push: {}
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        php-versions: ["7.4", "8.0", "8.1", "8.2"]
        phpunit-versions: ["latest"]
        include:
          - operating-system: "ubuntu-latest"
            php-versions: "7.2"
            phpunit-versions: "8.5.21"
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: php-cs-fixer, phpunit:${{ matrix.phpunit-versions }}

      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

      - name: Install dependencies
        run: composer install

      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        with:
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text
        run: phpunit 

